### ISSUE TITLE
Quoting issues in ES template can break idempotence

### ISSUE THREAD

**Issue by alexharv074** [elastic/puppet-elasticsearch#957]
## Version information

* Module version: 6.3.0
* Puppet version: 4.10.12, 5.5.1
* OS and version: CentOS 7

## Bug description

Sometimes, for example when using the default Logstash 6.x Elasticsearch output template ([ref](https://github.com/logstash-plugins/logstash-output-elasticsearch/tree/master/lib/logstash/outputs/elasticsearch)), certain JSON fields are apparently converted from numbers or booleans into strings by Elasticsearch after the JSON template is uploaded via the REST API by the Elasticsearch Template type. Idempotence is then broken, because, apparently, the type then sees a data mismatch (i.e. the source template still says number or boolean, whereas the ES API returns data of type string).

## To reproduce

Take the latest Elasticsearch 6.x output template from [here](https://github.com/logstash-plugins/logstash-output-elasticsearch/tree/master/lib/logstash/outputs/elasticsearch).

Declare this file as an Elasticsearch template:

``` puppet
elasticsearch::template { 'logstash':
  source => 'puppet:///path/to/logstash.json',
}
```

Then puppet apply it twice.

## What I expect to see

This code should be idempotent, i.e. on the second puppet apply, there should not be changes.

## What I actually see 

On the second run:

```
[root@centos-72-x64 ~]# puppet apply /tmp/apply_manifest.pp.VltrGo 
Notice: Compiled catalog for centos-72-x64.macquarie.local in environment production in 1.46 seconds
Notice: /Stage[main]/Profile::Elasticsearch::Data_node/Elasticsearch::Template[logstash]/Elasticsearch_template[logstash]/content: content changed {'aliases' => {}, 'index_patterns' => ['*'], 'mappings' => {'_default_' => {'dynamic_templates' => [{'message_field' => {'mapping' => {'norms' => 'false', 'type' => 'text'}, 'match_mapping_type' => 'string', 'path_match' => 'message'}}, {'string_fields' => {'mapping' => {'fields' => {'keyword' => {'ignore_above' => '256', 'type' => 'keyword'}}, 'norms' => 'false', 'type' => 'text'}, 'match' => '*', 'match_mapping_type' => 'string'}}], 'properties' => {'@timestamp' => {'type' => 'date'}, '@version' => {'type' => 'keyword'}, 'geoip' => {'dynamic' => 'true', 'properties' => {'ip' => {'type' => 'ip'}, 'latitude' => {'type' => 'half_float'}, 'location' => {'type' => 'geo_point'}, 'longitude' => {'type' => 'half_float'}}}}}}, 'order' => '0', 'settings' => {'index' => {'number_of_replicas' => '0', 'refresh_interval' => '5s'}}, 'version' => '60001'} to '{"order"=>0, "aliases"=>{}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}, "template"=>"logstash-*", "version"=>60001, "index_patterns"=>["*"], "settings"=>{"index"=>{"refresh_interval"=>"5s", "number_of_replicas"=>0}}}'
Notice: Applied catalog in 1.49 seconds
```

## Further analysis

If I take the information about the changed hash from the Puppet output log, and pretty-print (actually awesome_print) the HashDiff here using the following Ruby code:

``` ruby
require 'awesome_print'
require 'hashdiff'
a = {'aliases' => {}, 'index_patterns' => ['*'], 'mappings' => {'_default_' => {'dynamic_templates' => [{'message_field' => {'mapping' => {'norms' => 'false', 'type' => 'text'}, 'match_mapping_type' => 'string', 'path_match' => 'message'}}, {'string_fields' => {'mapping' => {'fields' => {'keyword' => {'ignore_above' => '256', 'type' => 'keyword'}}, 'norms' => 'false', 'type' => 'text'}, 'match' => '*', 'match_mapping_type' => 'string'}}], 'properties' => {'@timestamp' => {'type' => 'date'}, '@version' => {'type' => 'keyword'}, 'geoip' => {'dynamic' => 'true', 'properties' => {'ip' => {'type' => 'ip'}, 'latitude' => {'type' => 'half_float'}, 'location' => {'type' => 'geo_point'}, 'longitude' => {'type' => 'half_float'}}}}}}, 'order' => '0', 'settings' => {'index' => {'number_of_replicas' => '0', 'refresh_interval' => '5s'}}, 'version' => '60001'}
b = {"order"=>0, "aliases"=>{}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}, "template"=>"logstash-*", "version"=>60001, "index_patterns"=>["*"], "settings"=>{"index"=>{"refresh_interval"=>"5s", "number_of_replicas"=>0}}}
ap HashDiff.diff(a,b)
```

I get: 

```
[
    [0] [
        [0] "~",
        [1] "mappings._default_.dynamic_templates[0].message_field.mapping.norms",
        [2] "false",
        [3] false
    ],
    [1] [
        [0] "-",
        [1] "mappings._default_.dynamic_templates[1]",
        [2] {
            "string_fields" => {
                           "mapping" => {
                    "fields" => {
                        "keyword" => {
                            "ignore_above" => "256",
                                    "type" => "keyword"
                        }
                    },
                     "norms" => "false",
                      "type" => "text"
                },
                             "match" => "*",
                "match_mapping_type" => "string"
            }
        }
    ],
    [2] [
        [0] "+",
        [1] "mappings._default_.dynamic_templates[1]",
        [2] {
            "string_fields" => {
                             "match" => "*",
                "match_mapping_type" => "string",
                           "mapping" => {
                      "type" => "text",
                     "norms" => false,
                    "fields" => {
                        "keyword" => {
                                    "type" => "keyword",
                            "ignore_above" => 256
                        }
                    }
                }
            }
        }
    ],
    [3] [
        [0] "~",
        [1] "mappings._default_.properties.geoip.dynamic",
        [2] "true",
        [3] true
    ],
    [4] [
        [0] "~",
        [1] "order",
        [2] "0",
        [3] 0
    ],
    [5] [
        [0] "~",
        [1] "settings.index.number_of_replicas",
        [2] "0",
        [3] 0
    ],
    [6] [
        [0] "~",
        [1] "version",
        [2] "60001",
        [3] 60001
    ],
    [7] [
        [0] "+",
        [1] "template",
        [2] "logstash-*"
    ]
]
```

However those diffs are misleading, because some of them relate to the type simply reformatting output for printing only - changes that  don't break idempotence ; and others of them relate to differences that do break idempotence.

## Workaround

This is the diff require to patch the actual file, so as not to break idempotence:
 
``` diff
--- a/site/modules/profile/files/logstash/logstash.json
+++ b/site/modules/profile/files/logstash/logstash.json
@@ -1,10 +1,9 @@
 {
-  "template": "logstash-*",
   "version": 60001,
   "index_patterns": ["*"],
   "settings": {
     "index.refresh_interval": "5s",
-    "index.number_of_replicas": 0
+    "index.number_of_replicas": "0"
   },
   "mappings": {
     "_default_": {
@@ -15,7 +14,7 @@
             "match_mapping_type": "string",
             "mapping": {
               "type": "text",
-              "norms": false
+              "norms": "false"
             }
           }
         },
@@ -24,7 +23,7 @@
             "match": "*",
             "match_mapping_type": "string",
             "mapping": {
-              "type": "text", "norms": false,
+              "type": "text", "norms": "false",
               "fields": {
                 "keyword": { "type": "keyword", "ignore_above": 256 }
               }
@@ -36,7 +35,7 @@
         "@timestamp": { "type": "date"},
         "@version": { "type": "keyword"},
         "geoip": {
-          "dynamic": true,
+          "dynamic": "true",
           "properties": {
             "ip": { "type": "ip" },
             "location": { "type": "geo_point" },
```

In other words, I had to:
- delete the template field (why?)
- convert _all_ JSON _booleans_ to strings, i.e. replace true with "true" and false with "false"
- convert _some_ JSON _numbers_ to strings. In particular, I found when I added the index.number_of_replicas I had to quote that field as a string "0" instead of 0.

The final version of the working JSON template is:

``` json
{
  "version": 60001,
  "index_patterns": ["*"],
  "settings": {
    "index.refresh_interval": "5s",
    "index.number_of_replicas": "0"
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "message_field": {
            "path_match": "message",
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "norms": "false"
            }
          }
        },
        {
          "string_fields": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "text", "norms": "false",
              "fields": {
                "keyword": { "type": "keyword", "ignore_above": 256 }
              }
            }
          }
        }
      ],
      "properties": {
        "@timestamp": { "type": "date"},
        "@version": { "type": "keyword"},
        "geoip": {
          "dynamic": "true",
          "properties": {
            "ip": { "type": "ip" },
            "location": { "type": "geo_point" },
            "latitude": { "type": "half_float" },
            "longitude": { "type": "half_float" }
          }
        }
      }
    }
  }
}
```

**Comment by tylerjl** [comment]
The underlying cause here, as you mention, is that while users can specify a template hash/json with boolean or integer datatypes, the Elasticsearch API normalizes all fields to be strings. If you look at the native provider type, [the `munge` method takes steps to parse out integers](https://github.com/tylerjl/puppet-elasticsearch/blob/26981a5db7583ab96d7d4349cd42f7d299baa01b/lib/puppet/type/elasticsearch_template.rb#L28-L60) to help keep the comparison between a) the hash that the user provides and b) the JSON structure that Elasticsearch returns consistent enough to detect changes but not raise a false out-of-sync comparison.

The fact that valid json can specify raw boolean types probably means that we just need to normalize the incoming hashes for the native provider to have just string values rather than try to catch every value into its native type, which is much more prone to problems than just normalizing on strings everywhere the way the Elasticsearch API does it.

This should be fairly easy to reproduce in a test case; I'll see about writing a test and fix for it.

**Comment by alexharv074** [comment]
I think it may not be as simple as that, but I'm not certain. Anyhow, I updated the bug description to be a bit clearer, and also provided the final version of the working JSON.

In particular, note this bit:

> I had to:
> 
> - delete the template field (why?)
> - convert _all_ JSON _booleans_ to strings, i.e. replace true with "true" and false with "false"
> - convert _some_ JSON _numbers_ to strings. In particular, I found when I added the index.number_of_replicas I had to quote that field as a string "0" instead of 0.

**Comment by tylerjl** [comment]
> delete the template field (why?)

The `template` field is a holdover from versions like 2.x of Elasticsearch - the template needs to use the `index_patterns` file to indicate which indices to match.

> convert all JSON booleans to strings, i.e. replace true with "true" and false with "false"

Yep, I think this can be caught by aggressively calling `to_s` on the hash values to unify everything on strings.

> convert some JSON numbers to strings. In particular, I found when I added the index.number_of_replicas I had to quote that field as a string "0" instead of 0.

The inconsistencies between what numbers are actual numeric types and which are strings should be resolved by just using `to_s` everywhere - I'm not sure why this field may have been causing a false `insync?`, but normalizing both the user input side and what is returned from Elasticsearch should keep them the same.

[I have a branch here under `native-type-to-strings`](https://github.com/elastic/puppet-elasticsearch/tree/native-type-to-strings) with some fixes and tests to catch and potentially fix the behavior you're seeing here. I believe the updated tests should catch the behavior you're describing, but I would feel more confident about it if you could confirm that the changes in that branch resolve the problem. Would you mind trying out the branch to see if it helps?

**Comment by alexharv074** [comment]
It works!

The only remaining problem, then, is that the default Logstash ES output [here](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template-es6x.json) needs to have the `template` field converted to `index_patterns`. (At least, that is the only problem remaining with it that I can spot!)

**Comment by tylerjl** [comment]
Great, thank you for testing it out!

The template that you mention probably just needs to be changed upstream in that repo, correct? Based upon the 6.x docs, `index_patterns` is supported from 6.0 onwards so the upstream logstash template probably needs to be changed.

If that all sounds good I can PR the change to get it in to the module.

**Comment by alexharv074** [comment]
I suppose so. Is that upstream project not official, owned by Elastic.co etc? I don't know much about it.

**Comment by alexharv074** [comment]
And thanks for fixing the bug so quickly! :)

**Comment by tylerjl** [comment]
It looks like [there's already a PR submitted to fix this](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/707), so we probably just need to ping upstream to take a look again (the logstash-plugins GitHub group still is mostly operated by Elastic's logstash engineers, so we should be able to get it in).

Regardless, the Puppet side of this bug should be resolved with that branch, so I'll PR it and let the tests bake in Travis to confirm everything looks good.

**Comment by alexharv074** [comment]
Great, thanks again. 👍

**Comment by tylerjl** [comment]
Fix merged in #958, will go out in the next release.

**Comment by alexharv074** [comment]
@tylerjl ,

Sorry, I am not sure if I did something wrong when I tested it before, or if something else changed, but, in any case, I just ran into the following issue when using the patched code:

```
Error: /Stage[main]/Profile::Elasticsearch::Data_node/Elasticsearch::Template[logstash]/Elasticsearch_template[logstash]: Could not evaluate: Elasticsearch API responded with: Malformed [version] value, should be an integer
```

I can get past this by simply deleting the version field from the template.

I guess the Elasticsearch API does in fact require some of the data to be of types other than string.

**Comment by tylerjl** [comment]
Well shoot - I guess we'll need to preferentially parse out integers and let the string handling logic convert the rest. It shouldn't be hard - we can convert to strings, then sweep the number conversion logic, but I'll need to test it as well.
